#!/usr/bin/env python

import rospy
from path_ui import Path_Ui

if __name__ == '__main__':
    rospy.init_node('path_planning')
    path = [2.0, 0.5, 1.5, 1.0, 0.5, 2, 1.5, 2.7]
    ui = Path_Ui('robot.png', 3., 3., 300, -1.5, -1.5, path=path)
    ui.run()
